spring.application.name=knda-check
spring.profiles.default=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.schemas=knda_check
spring.flyway.default-schema=knda_check

